language: android
dist: trusty
android:
  components:
    - tools
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - extra-google-m2repository
    - extra-android-m2repository

script:
  - ./gradlew build connectedCheck

licenses:
  - '.+'
