language: android
dist: trusty
android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - extra-google-m2repository
    - extra-android-m2repository

script:
  - ./gradlew test

licenses:
  - '.+'
